BookShop.WebUI/Models/BookDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using BookShop.Domain.Concrete;
using BookShop.Domain.Entities;

namespace BookShop.WebUI.Models
{
    public class BookDbInitializer : DropCreateDatabaseAlways<EFDbContext>
    {
        protected override void Seed(EFDbContext db)
        {

            /*db.books.Add(new Book { BookName = "Война и мир", AuthorName = "Л. Толстой", Price = 220 });
            db.books.Add(new Book { BookName = "Отцы и дети", AuthorName = "И. Тургенев", Price = 180 });
            db.books.Add(new Book { BookName = "Чайка", AuthorName = "А. Чехов", Price = 150 });

            base.Seed(db);*/
        }
    }
}

BookShop.WebUI/Models/BooksListViewModel.cs
using BookShop.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookShop.WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; } 
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

BookShop.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BookShop.Domain.Entities;

namespace BookShop.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

BookShop.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookShop.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }

        public int ItemsPerPage { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

BookShop.WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.Domain.Abstract;
using BookShop.Domain.Entities;
using BookShop.WebUI.Models;

namespace BookShop.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 4;

        public BookController(IBookRepository repo)
        {
            repository = repo;
        }

        // GET: Book
        /*public ActionResult Index()
        {
            return View();
        }*/

        public ViewResult List(string category, int page=1)
        {

            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.books
                   .Where(p => category == null || p.Category == category)
                   .OrderBy(game => game.BookId)
                   .Skip((page - 1) * pageSize)
                   .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.books.Count() :
                    repository.books.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

BookShop.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.Domain.Entities;
using BookShop.Domain.Abstract;
using BookShop.WebUI.Models;
using System.Web.UI.WebControls;

namespace BookShop.WebUI.Controllers
{
    public class CartController : Controller
    {
        IBookRepository repository;
        IOrderProcessor orderProcessor; 

        public CartController(IBookRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }


        public ViewResult Index(Cart cart, string returnUrl) 
        {
            return View(new CartIndexViewModel()
            {
                Cart = cart, ReturnUrl = returnUrl
            });
        } 

        public RedirectToRouteResult AddToCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
           Book book = repository.books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

    }
}

BookShop.WebUI/Controllers/NavController.cs
using BookShop.Domain.Abstract;
using BookShop.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookShop.WebUI.Controllers
{
    public class NavController : Controller
    {
        IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.books
                .Where(book => book.Category != null)
                .Select(book => book.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

BookShop.WebUI/Views/Book/List.cshtml
@using BookShop.WebUI.Models
@using BookShop.WebUI.HtmlHelpers
@model BooksListViewModel
@{
    ViewBag.Title = "Books List";
}

@foreach (var p in @Model.Books) 
{
    @Html.Partial("BookSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", 
    new { page = x, category = Model.CurrentCategory }))
</div>

BookShop.WebUI/Views/Cart/Checkout.cshtml
@model BookShop.Domain.Entities.ShippingDetails


@{
    ViewBag.Title = "BookShop: Checkout";
}

<h2>Checkout right now</h2>

<p> please input your personal info for shipping</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>general</h3>
    <div class="form-group"> 
        <label> your name </label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Address</h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Checkout" />
    </div>

}

BookShop.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

BookShop.WebUI/Views/Cart/Index.cshtml
@model BookShop.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "BookShop: Cart";
}

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Your Cart</h2>

<table id="cartTable" class="table"> 
    <thead>
        <tr>
            <th>Quantity</th> 
            <th>Name</th> 
            <th class="text-right">Price</th> 
            <th class="text-right">Total Price</th> 
        </tr>
    </thead>

    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.BookName</td>
                <td class="text-right">@line.Book.Price.ToString("# руб")</td>
                <td class="text-right">
                    @((line.Quantity * line.Book.Price).ToString("# руб"))
                </td>
                <td>@using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("BookId", line.Book.BookId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="delete" />
                }</td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# uah")
            </td>
        </tr>
    </tfoot>
    </table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Back To Shopping</a>
    @Html.ActionLink("Checkout", "Checkout", null, new { @class = "btn btn-primary"})
</div>

BookShop.WebUI/Views/Cart/Summary.cshtml
@model BookShop.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Order", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) books,
    @Model.ComputeTotalValue().ToString("# uah")
</div>

BookShop.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string> 

@Html.ActionLink("Home", "List", "Book", 
    null, new { @class = "btn btn-block btn-default btn-lg"})

@foreach(var link in Model)
{
    @Html.RouteLink(link,
    new { controller = "Book", action = "List", category=link, page = 1},
    new { @class = "btn btn-block btn-default btn-lg"
    + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}  

BookShop.WebUI/Views/Shared/BookSummary.cshtml
@model BookShop.Domain.Entities.Book

<div class="well">
    <h3>
        <strong>@Model.BookName</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# uah")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">

            @Html.HiddenFor(b => b.BookId )
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart"/>
            </div>
    }

    <span class="lead"> @Model.Description</span>
</div>

BookShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">BookShop - educational e-commerce</a>
        @Html.Action("Summary", "Cart")
        </div>

    <div class="row panel"> 
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
    <div class="col-xs-8">
        @RenderBody()
        </div>
    </div>
</body>
</html>